# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('priority-queue', ['core'])
    module.source = [
        'model/priority-queue-model.cc',
        'model/priority-queue-receiver.cc',
        'model/priority-queue-sender.cc',
        'helper/priority-queue-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('priority-queue')
    module_test.source = [
        'test/priority-queue-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'priority-queue'
    headers.source = [
        'model/priority-queue-model.h',
        'model/priority-queue-receiver.h',
        'model/priority-queue-sender.h',
        'helper/priority-queue-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

