# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('processing-delay', ['core','point-to-point', 'network', 'applications'])
    module.source = [
        'model/processing-delay-model.cc',
        'model/processing-delay-sender.cc',
        'model/processing-delay-receiver.cc',
        'helper/processing-delay-sender-receiver-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('processing-delay')
    module_test.source = [
        'test/processing-delay-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'processing-delay'
    headers.source = [
        'model/processing-delay-model.h',
        'model/processing-delay-sender.h',
        'model/processing-delay-receiver.h',
        'helper/processing-delay-sender-receiver-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

